import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";

describe("Electron preload contract", () => {
  it("uses a CommonJS preload file so Electron can load the bridge", async () => {
    const preloadSource = await readFile("electron/preload.cjs", "utf8");
    const mainSource = await readFile("electron/main.ts", "utf8");

    expect(preloadSource).toContain("require(\"electron\")");
    expect(preloadSource).toContain("contextBridge.exposeInMainWorld(\"modelLibrary\"");
    expect(preloadSource).toContain("readModelMetadata");
    expect(preloadSource).toContain("readModelThumbnail");
    expect(preloadSource).toContain("readImageDataUrl");
    expect(preloadSource).toContain("readImageDataUrl: (session, absolutePath)");
    expect(preloadSource).toContain('ipcRenderer.invoke("image:read-data-url"');
    expect(preloadSource).toContain("readObjPreviewFile: (session, absolutePath)");
    expect(preloadSource).toContain('ipcRenderer.invoke("obj:read-preview-file"');
    expect(preloadSource).toContain("openLibraryFile");
    expect(preloadSource).toContain("openLibraryFile: (session, absolutePath)");
    expect(preloadSource).toContain('ipcRenderer.invoke("system:open-library-file"');
    expect(preloadSource).toContain('ipcRenderer.invoke("library:show-folder", session, relativeFolder)');
    expect(mainSource).toContain('ipcMain.handle("library:show-folder"');
    expect(preloadSource).toContain("readCachedThumbnail");
    expect(preloadSource).toContain("writeCachedThumbnail");
    expect(preloadSource).toContain("cleanUnusedThumbnails: (session, models)");
    expect(preloadSource).toContain('ipcRenderer.invoke("thumbnail:clean-library", session, models)');
    expect(preloadSource).toContain('ipcRenderer.invoke("thumbnail:cache-invalidate"');
    expect(mainSource).toContain('ipcMain.handle("thumbnail:cache-invalidate"');
    expect(preloadSource).toContain("activateLibrary");
    expect(preloadSource).toContain("getCurrentLibrary");
    expect(preloadSource).toContain('ipcRenderer.invoke("library:current")');
    expect(preloadSource).toContain('ipcRenderer.invoke("library:activate"');
    expect(preloadSource).toContain('ipcRenderer.invoke("library:scan", session)');
    expect(preloadSource).toContain("verifyLibrary: (session)");
    expect(preloadSource).toContain('ipcRenderer.invoke("library:verify", session)');
    expect(preloadSource).toContain("rebuildLibraryIndex: (session)");
    expect(preloadSource).toContain('ipcRenderer.invoke("library:rebuild-index", session)');
    expect(preloadSource).toContain("showLibraryDataFolder: (session)");
    expect(preloadSource).toContain('ipcRenderer.invoke("library:show-data-folder", session)');
    expect(preloadSource).toContain("setLibraryMonitoring");
    expect(preloadSource).toContain("onLibraryChanged");
    expect(preloadSource).toContain("callback(payload)");
    expect(preloadSource).toContain("saveConvertedStl");
    expect(preloadSource).toContain("chooseArchiveExtractor");
    expect(preloadSource).toContain("detectSlicers");
    expect(preloadSource).toContain("inspectConfiguredSlicers");
    expect(preloadSource).toContain('ipcRenderer.invoke("slicer:detect")');
    expect(mainSource).toContain('ipcMain.handle("slicer:detect"');
    expect(preloadSource).toContain("startFileDrag");
    expect(preloadSource).toContain("onFileDragStatus");
    expect(preloadSource).toContain('ipcRenderer.on("model:file-drag-status"');
    expect(preloadSource).toContain("listArchiveEntries");
    expect(preloadSource).toContain("extractArchiveEntries");
    expect(preloadSource).toContain("extractArchive");
    expect(preloadSource).toContain('ipcRenderer.invoke("archive:extract-all"');
    expect(mainSource).toMatch(/ipcMain\.handle\(\s*"archive:extract-all"/);
    expect(preloadSource).toContain("getModelHashes");
    expect(preloadSource).toContain("createFolder");
    expect(preloadSource).toContain("moveModels");
    expect(preloadSource).toContain("moveFolder");
    expect(preloadSource).toContain("renameFolder");
    expect(preloadSource).toContain("trashFolder");
    expect(preloadSource).toContain("renameModelFile");
    expect(preloadSource).toContain("trashModels");
    expect(preloadSource).toContain("restoreLibraryPaths");
    expect(preloadSource).toContain("getLibraryMetadata");
    expect(preloadSource).toContain("getLibraryMetadataStatus");
    expect(preloadSource).toContain('ipcRenderer.invoke("metadata:status")');
    expect(preloadSource).toContain("retryLibraryMetadata");
    expect(preloadSource).toContain('ipcRenderer.invoke("metadata:retry")');
    expect(preloadSource).toContain("toggleFavorite");
    expect(preloadSource).toContain("setModelTags");
    expect(preloadSource).toContain("addCatalogTag");
    expect(preloadSource).toContain("removeCatalogTag");
    expect(preloadSource).toContain("setModelNotes");
    expect(preloadSource).toContain("getLibraryDataStatus");
    expect(preloadSource).toContain('ipcRenderer.invoke("metadata:data-status")');
    expect(preloadSource).toContain("exportLibraryBackup: (session)");
    expect(preloadSource).toContain('ipcRenderer.invoke("metadata:export-backup", session)');
    expect(preloadSource).toContain("restoreLibraryBackup: (session)");
    expect(preloadSource).toContain('ipcRenderer.invoke("metadata:restore-backup", session)');
    expect(mainSource).toContain('ipcMain.handle("metadata:data-status"');
    expect(mainSource).toMatch(/ipcMain\.handle\(\s*"metadata:export-backup"/);
    expect(mainSource).toMatch(/ipcMain\.handle\(\s*"metadata:restore-backup"/);
    expect(preloadSource).toContain("showModelInFolder");
    expect(preloadSource).toContain("copyText");
    expect(preloadSource).toContain("getRuntimeVersions");
    expect(preloadSource).toContain('ipcRenderer.invoke("system:runtime-versions")');
    expect(mainSource).toContain('ipcMain.handle("system:runtime-versions"');
    expect(mainSource).toContain('ipcMain.handle("image:read-data-url"');
    expect(mainSource).toContain('ipcMain.handle("obj:read-preview-file"');
    expect(mainSource).toContain('ipcMain.handle("system:open-library-file"');
    expect(mainSource).toContain("nativeImage.createFromBuffer");
    expect(mainSource).toContain("maxImageBytes: MAX_DIRECT_IMAGE_BYTES");
    expect(mainSource).toContain("app.getVersion()");
    expect(mainSource).toContain("process.versions.electron");
    expect(mainSource).toContain("process.versions.chrome");
    expect(preloadSource).toContain('ipcRenderer.invoke("system:copy-text"');
    expect(preloadSource).not.toContain("import ");
  });

  it("isolates the renderer and prevents navigation-based privilege changes", async () => {
    const mainSource = await readFile("electron/main.ts", "utf8");
    const htmlSource = await readFile("index.html", "utf8");

    expect(mainSource).toContain("sandbox: true");
    expect(mainSource).toContain("navigateOnDragDrop: false");
    expect(mainSource).toContain("configureWindowSecurity(window.webContents, rendererUrl)");
    expect(htmlSource).toMatch(/http-equiv=["']Content-Security-Policy["']/);
    expect(htmlSource).toContain("object-src 'none'");
    expect(htmlSource).toContain("frame-src 'none'");
    expect(htmlSource).toContain("base-uri 'none'");
  });
});
